//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D3DLab.Viewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class ViewerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ViewerSettings defaultInstance = ((ViewerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ViewerSettings())));
        
        public static ViewerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentFilePaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentFilePaths"]));
            }
            set {
                this["RecentFilePaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ObjGroupFilters {
            get {
                return ((string)(this["ObjGroupFilters"]));
            }
            set {
                this["ObjGroupFilters"] = value;
            }
        }
    }
}
